### ISSUE TITLE
Merge and call_jags script

### ISSUE THREAD

**Issue by williash23** [Lukacs-Lab/Columbia-Spotted-Frogs#19]
I may or may not have just severely screwed something up with an unintentional merge. From Git on my own computer and from what I can see on the Lukacs Lab master - the most up to date code is in fact correctly on here. Hoping it didn't screw anyone else's stuff up....

If anyone (slash Josh :) ) wants to take a look at the "call_jags" script in the model folder and see if I took the right stuff out of the model scripts and put them into the call_jags script, that'd be sweet.

**Comment by Huh** [comment]
That is why we have version control and...there is a revert button on the website  
Josh Nowak 

```
 On Thursday, April 23, 2015 12:59 PM, Sara Williams <notifications@github.com> wrote:
```

 I may or may not have just severely screwed something up with an unintentional merge. From Git on my own computer and from what I can see on the Lukacs Lab master - the most up to date code is in fact correctly on here. Hoping it didn't screw anyone else's stuff up....If anyone (slash Josh :) ) wants to take a look at the "call_jags" script in the model folder and see if I took the right stuff out of the model scripts and put them into the call_jags script, that'd be sweet.—

**Comment by Huh** [comment]
Can we close this?

**Comment by williash23** [comment]
Yep

**Comment by Huh** [comment]
Holy cow that fast
