### ISSUE TITLE
Issues with running analysis

### ISSUE THREAD

**Issue by williash23** [Lukacs-Lab/Columbia-Spotted-Frogs#43]
Holla - 

So, we are still having some issues with the actual running of the analysis. I think it's related to initial values of z. We discussed adding a "first" event slection in the actual model code, which I did. Here is where we are at:

In the call_jags script: Created a new object.
first_occ <- tapply(prim, ind, min)
This is an array; and is passed to JAGS along with the other data (it's in the bundle data list).

In the actual model:
    #  Likelihood
            for(i in 1:n_ind){
        for(j in first_occ[i]:n_prim){
          z[i,j] ~ dbern(phi[i,j])
        }
      }

And here is the error:
![image](https://cloud.githubusercontent.com/assets/11653020/8089216/b7ab32de-0f63-11e5-9ac4-1965131f710b.png)

Thoughts?

**Comment by williash23** [comment]
First try at fix didn't work.

Now:
        z.init <- function(n_ind=n_ind, first_occ=first_occ, prim=prim, y=y){
            z <- matrix(NA, nrow = n_ind, ncol = n_prim)
            for(i in 1:n_ind){
                z[i, first_occ[i]:n_prim] <- 1
                }
        }

Result when in debug_mode:
![image](https://cloud.githubusercontent.com/assets/11653020/8089834/8a873664-0f67-11e5-92f6-99d09df9ae9c.png)
(That's it)

Result when not in debug_mode:
![image](https://cloud.githubusercontent.com/assets/11653020/8089850/9900fe28-0f67-11e5-9175-ce11513ab39e.png)

**Comment by Huh** [comment]
It looks like the dimensions of z and n_ind are not the same in the model.  Check that dimensions of z conform to the data used to loop. Josh Nowak 

```
 On Wednesday, June 10, 2015 11:28 AM, Sara Williams <notifications@github.com> wrote:
```

 Holla - So, we are still having some issues with the actual running of the analysis. I think it's related to initial values of z. We discussed adding a "first" event slection in the actual model code, which I did. Here is where we are at:In the call_jags script: Created a new object.
first_occ <- tapply(prim, ind, min)
This is an array; and is passed to JAGS along with the other data (it's in the bundle data list).In the actual model:
 # Likelihood
 for(i in 1:n_ind){
 for(j in first_occ[i]:n_prim){
 z[i,j] ~ dbern(phi[i,j])
 }
 }And here is the error:
Thoughts?—
