### ISSUE TITLE
Models with sex covariate

### ISSUE THREAD

**Issue by williash23** [Lukacs-Lab/Columbia-Spotted-Frogs#53]
Hey peeps - 

I think we are good on convergence and runs for all models except those that use the sex covariate. Here, we still have a data issue. Since only a small number of frogs have a sex recorded, we need to run through the vectors of weight, length and toe and select the observations that coincide with the frogs that also have sex recorded. Does that make sense? Any ideas anyone?

**Comment by williash23** [comment]
Here is the code from the call_jags script to get the sex covariate in order:

```
    # This is the correct way to get sex, but because there are fewer 
    # individuals in this data it needs to be used to create all the data
    # above too
    sex <- tapply(fsex$Sex, as.numeric(as.factor(fsex$Index)), function(x){
            ifelse(unique(x) == "M", 0, 1)
    })
```

**Comment by Huh** [comment]
I would probably do something like...
sex_index <- data %>%  group_by(Index) %>% summarise(sex_info = any(!is.na(sex)))#  Then use sex_index to subset all the covariate data and the encounter histories

#  For examplelength <- length %>% filter(Index %in% sex_index$Index)

#  And change the character to numeric or it won't work....as you did above, just differentsex_dat <- fsex %>% group_by(Index) %>% mutate(sex = ifelse(x == "M", 0, 1))

Hopefully that helps, if you want a non-dplyr solution let me know Josh Nowak 

```
 On Thursday, June 18, 2015 4:17 PM, Sara Williams <notifications@github.com> wrote:
```

 Here is the code from the call_jags script to get the sex covariate in order:    # This is the correct way to get sex, but because there are fewer 
    # individuals in this data it needs to be used to create all the data
    # above too
    sex <- tapply(fsex$Sex, as.numeric(as.factor(fsex$Index)), function(x){
            ifelse(unique(x) == "M", 0, 1)
    })

**Comment by williash23** [comment]
I still need help...I'm trying to make this work but sadly incapable on my own. :(

**Comment by Huh** [comment]
I am at work if you want/need to chat.  If you would like to schedule something for later in the week that would be fine too. Josh Nowak 

```
 On Monday, June 22, 2015 11:28 AM, Sara Williams <notifications@github.com> wrote:
```

 I still need help...I'm trying to make this work but sadly incapable on my own. :(—

**Comment by williash23** [comment]
Sweet, thanks! I'm futzing a bit more on it (final attempts) and if I can't get it, I will likely see you up there this PM.

**Comment by williash23** [comment]
What WHAT!

Maybe I got it. (Or maybe not). Will you all look at this and see if it looks right to you as well? 

```
    ############# Data for all covariates when using sex ############################
    # This is the correct way to get sex, but because there are fewer 
    # individuals in this data it needs to be used to create all the data
    # above too
    sex_num <- tapply(fsex$Sex, as.numeric(as.factor(fsex$Index)), function(x){
            ifelse(unique(x) == "M", 0, 1)
    })
    sex_num <- as.data.frame(sex_num)

    sex_index <- fsex %>%  
                group_by(Index) %>% 
                summarise(sex_info = any(!is.na(Sex)))  

    temp <- bind_cols(sex_index, sex_num)

    sex_dat <- inner_join(fsex, temp, by = "Index")
    sex_dat <- select(sex_dat, -sex_info)

    ind<- as.factor(sex_dat$Index)
    ind <- as.numeric(ind)

    sex <- as.numeric(tapply(as.numeric(sex_dat$sex_num), ind, unique))
    toe <- as.numeric(tapply(as.numeric(sex_dat$toes), ind, unique))
    toe <- as.numeric(scale(toe))
    length <- as.numeric(tapply(as.numeric(sex_dat$sc_len), ind, unique))
    weight <- as.numeric(tapply(as.numeric(sex_dat$sc_wt), ind, unique))
```

**Comment by williash23** [comment]
Realized I have to re-select ALL the pieces of data...here is the final code I'm using for this part:

```
    ############# Data selection for all covariates when using sex ############################

    #  There are fewer that have sex recorded than in the total data set. So, we have to recreate all
    #   the data and covariate vectors with this smaller subset of data, and it has to be taken for
    #   the correct individuals (i.e., not just the first 463 individuals, but the 463 that also have
    #   sex recorded)
    sex_num <- tapply(fsex$Sex, as.numeric(as.factor(fsex$Index)), function(x){
            ifelse(unique(x) == "M", 0, 1)
    })
    sex_num <- as.data.frame(sex_num)

    sex_index <- fsex %>%  
                        group_by(Index) %>% 
                        summarise(sex_info = any(!is.na(Sex)))  

    temp <- bind_cols(sex_index, sex_num)

    sex_dat <- inner_join(fsex, temp, by = "Index")
    sex_dat <- select(sex_dat, -sex_info)


    y <- as.numeric(sex_dat$cap)    
    ind<- as.factor(sex_dat$Index)
    ind <- as.numeric(ind)
    prim <- as.factor(sex_dat$prim)
    prim <- as.numeric(prim)
    sec <- as.factor(sex_dat$sec)
    sec <- as.numeric(sec)

    n_obs <- nrow(sex_dat)
    n_ind <- length(unique(sex_dat$Index))
    n_prim <- length(unique(prim))
    n_sec <- rep(NA,n_prim) 
    for(i in 1:n_prim){
        n_sec[i] <- length(unique(sec[prim == i]))
    }

    first_occ <- as.numeric(tapply(prim, ind, min))

    sex <- as.numeric(tapply(as.numeric(sex_dat$sex_num), ind, unique))
    toe <- as.numeric(tapply(as.numeric(sex_dat$toes), ind, unique))
    toe <- as.numeric(scale(toe))
    length <- as.numeric(tapply(as.numeric(sex_dat$sc_len), ind, unique))
    weight <- as.numeric(tapply(as.numeric(sex_dat$sc_wt), ind, unique))
```

**Comment by Huh** [comment]
It looks good to me, but without playing with it my confidence is not super high.  The original sex_num is not the greatest because those individuals without information will receive a 1.  I like the sex_index formulation much better.  I might combine the two....something like...
    sex_index <- fsex %>%  
                group_by(Index) %>%                filter(!is.na(Index)) %>% 
                mutate(sex_num = switch(as.character(Sex), "F" = 0, "M" = 1))As for the rest of it, it looks good.  For the sake of maintaining similar syntax I might have written something like...    sex_dat <- inner_join(fsex, sex_index, by = "Index") %>%                #  then if appropriate you could just
                group_by(Index) %>%
                summarise(sex = unique(sex),
                            toe = scale(unique(toes)),
                            length = scale(unique(length)),
                            weight = scale(unique(weight))) 
 
Hope that helps, what you wrote looks good, but that first bit (which I think I actually wrote) is bothering me at the moment.Josh Nowak 

```
 On Monday, June 22, 2015 2:32 PM, Sara Williams <notifications@github.com> wrote:
```

 What WHAT!Maybe I got it. (Or maybe not). Will you all look at this and see if it looks right to you as well?     ############# Data for all covariates when using sex ############################
    # This is the correct way to get sex, but because there are fewer 
    # individuals in this data it needs to be used to create all the data
    # above too
    sex_num <- tapply(fsex$Sex, as.numeric(as.factor(fsex$Index)), function(x){
            ifelse(unique(x) == "M", 0, 1)
    })
    sex_num <- as.data.frame(sex_num)

```
sex_index <- fsex %>%  
            group_by(Index) %>% 
            summarise(sex_info = any(!is.na(Sex)))  

temp <- bind_cols(sex_index, sex_num)

sex_dat <- inner_join(fsex, temp, by = "Index")
sex_dat <- select(sex_dat, -sex_info)

ind<- as.factor(sex_dat$Index)
ind <- as.numeric(ind)

sex <- as.numeric(tapply(as.numeric(sex_dat$sex_num), ind, unique))
toe <- as.numeric(tapply(as.numeric(sex_dat$toes), ind, unique))
toe <- as.numeric(scale(toe))
length <- as.numeric(tapply(as.numeric(sex_dat$sc_len), ind, unique))
weight <- as.numeric(tapply(as.numeric(sex_dat$sc_wt), ind, unique))
```
